django_yibiao/django_yibiao/urls.py
from django.contrib import admin
from django.urls import path
from my_app.views import meter,admin,yibiao,account,model_template,ocr,well
from django.urls import path,re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [

    # 配置media
    re_path(r'^yibiao_ocr/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}, name='yibiao_ocr'),

    path('meter/', meter.index),

    # 登录
    path('login/', account.login),
    path('logout/', account.logout),  # 注销
    path('image/code/', account.image_code),  # 生成图像验证码

    # 用户
    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.admin_add),
    path('user/add/', admin.user_add),   # 用户注册
    path('admin/<int:aid>/edit/', admin.admin_edit),
    path('user/<int:aid>/edit/', admin.user_edit), # 用户更新
    path('admin/del/', admin.admin_del),
    path('admin/<int:aid>/reset/', admin.admin_reset),
    path('user/<int:aid>/reset/', admin.user_reset), # 用户更新密码

    # 仪表图像处理
    path('', yibiao.yibiao_list),  # 仪表列表（设置为成为默认的启动地址）
    # path('yibiao/list/', yibiao.yibiao_list),
    path('yibiao/add/',yibiao.yibiao_add),                # 上传仪表图像
    path('yibiao/<int:yid>/del/',yibiao.yibiao_del),      # 删除仪表图像
    path('yibiao/<int:yid>/detect/',yibiao.yibiao_detect),# 仪表检测

    # 仪表模板图像处理
    path('model/list/',model_template.model_list),        # 仪表模板列表
    path('model/add/',model_template.model_add),
    path('model/edit/',model_template.model_edit),
    path('model/del/',model_template.model_del),
    path('model/detail/',model_template.model_detail),
    path('model/make_template_msg/',model_template.make_template_msg),

    # 文字识别
    path('ocr/',ocr.ocr),
    path('ocr/rec/',ocr.rec),
    path('ocr/list/',ocr.ocr_list),
    path('ocr/del/',ocr.ocr_del),

    # 小盖板识别
    path('well/',well.well),
    path('well/rec/',well.well_rec),
    path('well/list/',well.well_list),
    path('well/del/',well.well_del),



]

django_yibiao/my_app/models.py
from django.db import models
from django.utils.timezone import now
import datetime
import django

# Create your models here.

class Admin(models.Model):
    '''用户'''
    username = models.CharField(verbose_name="用户名",max_length=32)
    password = models.CharField(verbose_name="密码",max_length=64)

    role_choices = (
        (1,"用户"),
        (2,"管理员")
    )
    role = models.SmallIntegerField(verbose_name="角色",choices=role_choices,default=1)

    name = models.CharField(verbose_name="姓名", max_length=16)
    age = models.IntegerField(verbose_name="年龄")
    # 在django中做的约束
    gender_choices = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choices)
    mobile = models.CharField(verbose_name="手机号", max_length=32)
    create_time = models.DateField(verbose_name="创建时间",default=now)



    def __str__(self):  # 输出对象时显示username
        return self.username

class Yibiao(models.Model):
    '''仪表信息表'''
    # 本质上数据库也是CharField，会自动保存数据。  upload_to='img_test_2/' 表示文件会自动保存在yibiao_ocr目录下的img_test_2目录中
    img = models.FileField(verbose_name="仪表图片", max_length=128, upload_to='img_test_2/')

    # img_result decimal(10,2) 小数
    img_result = models.DecimalField(verbose_name="识别结果",max_digits=10,decimal_places=2,default=0)

    img_name = models.CharField(verbose_name="图片名称",max_length=128)

    # 会在数据库表中自动创建admin_id字段
    admin = models.ForeignKey(verbose_name="用户", to="Admin", to_field="id", on_delete=models.CASCADE)

class Imgtemplate(models.Model):
    '''模板信息表'''
    name = models.CharField(verbose_name="模板名称",max_length=128)

    '''模板参数信息'''
    c_x = models.DecimalField(verbose_name="圆心x像素坐标",max_digits=10,decimal_places=2,default=0)
    c_y = models.DecimalField(verbose_name="圆心y像素坐标",max_digits=10,decimal_places=2,default=0)
    a = models.CharField(verbose_name="刻度及其对应像素坐标",max_length=256)
    maxd = models.DecimalField(verbose_name="最大刻度值", max_digits=10,decimal_places=2,default=0)
    fir_d = models.DecimalField(verbose_name="配置0刻度线参数1", max_digits=10,decimal_places=2,default=0)
    sec_d = models.DecimalField(verbose_name="配置0刻度线参数2", max_digits=10,decimal_places=2,default=0)
    scale = models.DecimalField(verbose_name="刻度间隔", max_digits=10,decimal_places=2,default=0)
    img_template = models.FileField(verbose_name="模板图片", max_length=128, upload_to='TemplateLib/')

class ImgOcrRec(models.Model):
    '''ocr文字识别表'''
    img = models.FileField(verbose_name="识别图片", max_length=128, upload_to='rec/')

    img_result = models.TextField(verbose_name="识别结果")

    # 会在数据库表中自动创建admin_id字段
    admin = models.ForeignKey(verbose_name="用户", to="Admin", to_field="id", on_delete=models.CASCADE)

class WellDanger(models.Model):
    '''小盖板检测'''
    imgrec = models.FileField(verbose_name="识别图片", max_length=128, upload_to='yolov5_master/number/')

    imgresult = models.CharField(verbose_name="识别结果",max_length=128)

    # 会在数据库表中自动创建admin_id字段
    admin = models.ForeignKey(verbose_name="用户", to="Admin", to_field="id", on_delete=models.CASCADE)

django_yibiao/my_app/views/account.py
# 姓名：刘超
# 开发时间：2022/6/28 16:07
# -*- coding: utf-8 -*-
from django.shortcuts import render, HttpResponse, redirect
from my_app import models
from my_app.utils.pagination import Pagination
from django import forms
from my_app.utils.bootstrap import BootStrapForm
from my_app.utils.encrypt import md5
from my_app.utils.img_code import check_code
# 生成验证码时用
from io import BytesIO
import os

class LoginForm(BootStrapForm):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput,
        required=True    # 必填
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(render_value=True),   # render_value=True表示密码输入后不会置空
        required=True    # 必填
    )
    code = forms.CharField(
        label="验证码",
        widget=forms.TextInput,
        required=True  # 必填
    )

    def clean_password(self):
        pwd_md5 = md5(self.cleaned_data.get("password"))
        return pwd_md5


# class LoginModelForm(forms.ModelForm):
#     class Meta:
#         model = models.Admin
#         labels = ["username","password"]

def login(request):
    req_method = request.method
    if req_method == 'GET':
        form = LoginForm()
        return render(request, 'login.html', {"form": form})
    form = LoginForm(data=request.POST)
    if form.is_valid():
        # 验证成功，获取到的用户名和密码
        # print(form.cleaned_data)   # {'username': 'root', 'password': '4876931d2563f86d7abfa501e3a51554','code': 'YLCHV'}

        # 验证码的校验
        # pop('code')相当于删除cleaned_data字典中的code字段，
        # 删除是因为filter(**form.cleaned_data).first()数据库中没有code字段
        user_input_code = form.cleaned_data.pop('code')
        img_code = request.session.get('image_code',"")
        if user_input_code.upper() != img_code.upper():
            form.add_error("code", "验证码错误")  # form.add_error主动添加一个错误
            return render(request, 'login.html', {"form": form})

        # 去数据库校验用户名和密码是否正确，获取用户对象、没有数据为None
        # admin = models.Admin.objects.filter(username="xxx",password="xxx").first()
        admin = models.Admin.objects.filter(**form.cleaned_data).first()
        if not admin:  # 说明用户名和密码不存在
            # form.add_error("username", "用户名或密码错误")
            form.add_error("password","用户名或密码错误")     # form.add_error主动添加一个错误
            return render(request, 'login.html', {"form": form})

        # 用户名和密码正确
        # 网站生成随机字符串; 写到用户浏览器的cookie中；再写入到session中；
        request.session["info"] = {'id': admin.id, 'username': admin.username, "name": admin.name,'role': admin.get_role_display()}
        # session可以保存7天
        request.session.set_expiry(60 * 60 * 24 * 7)

        # return redirect("/yibiao/list/")
        return redirect("/")
    return render(request, 'login.html', {"form": form})

def logout(request):
    '''注销'''
    request.session.clear()
    return redirect("/login/")


def image_code(request):
    '''生成图像验证码'''

    os.chdir('E:\python\django_yibiao')  # 改变工作目录

    # 调用pillow函数，生成图片
    img,code_string = check_code()
    # print(code_string)  # YLCHV 每次都会变

    # 写入到自己的session中（以便于后续获取验证码再进行校验）
    request.session['image_code'] = code_string
    # 给session设置60s超时
    request.session.set_expiry(60)

    stream = BytesIO()
    img.save(stream,'png')
    return HttpResponse(stream.getvalue())

django_yibiao/my_app/views/admin.py
# 姓名：刘超
# 开发时间：2022/6/27 15:38
# -*- coding: utf-8 -*-

from django.shortcuts import render, HttpResponse, redirect
# from my_app.models import Department,UserInfo
from my_app import models
from my_app.utils.pagination import Pagination
from my_app.utils.form import AdminModelForm,AdminEditModelForm,AdminResetModelForm,UserModelForm,UserEditModelForm
from django.http import JsonResponse
# 免除post请求的csrf认证
from django.views.decorators.csrf import csrf_exempt
'''管理员接口'''

# 管理员列表
def admin_list(request):

    # admin = request.session.get("info")
    # admin = request.session["info"]
    # print(admin["id"])   # 8
    # print(admin["name"]) # root

    # 搜索
    data_dict = {}
    # 第二个值为默认值
    # search_data对用户名进行模糊查询
    search_data = request.GET.get("q","")  # search_data在没传入q值的时候为空
    if search_data: # search_data值不为空时
        data_dict['username__contains'] = search_data

    admin_list = models.Admin.objects.filter(**data_dict)
    # print(admin_list)

    # 页码组件类
    page_object = Pagination(request,admin_list,page_size=2)  # 每页最多显示2个数据

    render_data ={
        "search_data": search_data,
        "admin_list": page_object.page_queryset,  # 获取起止页所需数据
        "page_string": page_object.html()  # 页码所需要的html代码
    }

    return render(request, 'admin_list.html',render_data)

from django import forms
from django.core.exceptions import ValidationError
from my_app.utils.bootstrap import BootStrapModelForm




# 添加管理员
def admin_add(request):
    title = "新建管理员"
    req_method = request.method
    if req_method == 'GET':
        form = AdminModelForm()
        return render(request, 'public_xxx_add.html', {"title": title, "form": form})
    form = AdminModelForm(data=request.POST)
    if form.is_valid():  # 数据验证成功
        # print(form.cleaned_data)  # {'username': 'ttt', 'password': '122', 'confirm_password': '123'}
        form.save()
        return redirect("/admin/list/")
    return render(request, 'public_xxx_add.html', {"title": title, "form": form})

# 更新管理员
def admin_edit(request,aid):
    title = "更新管理员"
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        # return render(request,'error.html',{"msg": "数据不存在"})
        return redirect("/admin/list/")
    req_method = request.method
    if req_method == 'GET':
        form = AdminEditModelForm(instance=admin)
        return render(request, 'public_xxx_add.html', {"title": title,"form": form})
    form = AdminEditModelForm(data=request.POST,instance=admin)
    if form.is_valid():
        # 因为AdminEditModelForm中只定义了username这一个字段，所以更新时只会更新这一个值
        form.save()
        return redirect("/admin/list/")
    return render(request, 'public_xxx_add.html', {"title": title,"form": form})

# 删除管理员
def admin_del(request):
    aid = request.GET.get("id")
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        return render(request,'error.html',{"msg": "数据不存在"})
        # return redirect("/admin/list/")
    models.Admin.objects.filter(id=aid).delete()
    return redirect("/admin/list/")

# 重置密码
def admin_reset(request,aid):
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        # return render(request, 'error.html', {"msg": "数据不存在"})
        return redirect("/admin/list/")
    title = "重置密码 - {}".format(admin.username)
    req_method = request.method
    if req_method == 'GET':
        # form = AdminResetModelForm(instance=admin)      # 更新密码
        form = AdminResetModelForm()      #重置密码不让她看到原来的密码，让其显示为空
        return render(request, 'public_xxx_add.html', {"title": title,"form": form})
    form = AdminResetModelForm(data=request.POST,instance=admin)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request, 'public_xxx_add.html', {"title": title, "form": form})

# 用户注册
@csrf_exempt
def user_add(request):
    title = "用户注册"
    req_method = request.method
    if req_method == 'GET':
        form = UserModelForm()
        return render(request, 'register.html', {"title": title, "form": form})
    form = UserModelForm(data=request.POST)
    print(request.POST)
    if form.is_valid():  # 数据验证成功
        # print(form.cleaned_data)  # {'username': 'ttt', 'password': '122', 'confirm_password': '123'}
        form.save()
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})

# 更新用户
def user_edit(request,aid):
    # print('更新用户: ',request.method)
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        # return render(request,'error.html',{"msg": "数据不存在"})
        return JsonResponse({"status": False, "msg": "数据不存在，请刷新重试"})
    title = "个人资料 - {}".format(admin.name)
    req_method = request.method
    if req_method == 'GET':
        form = UserEditModelForm(instance=admin)
        return render(request, 'my_message.html', {"title": title,"form": form})
    form = UserEditModelForm(data=request.POST,instance=admin)
    # print('form: ',form)
    if form.is_valid():
        # 因为AdminEditModelForm中只定义了username这一个字段，所以更新时只会更新这一个值
        form.save()
        request.session["info"] = {'id': admin.id, 'username': form.instance.username, "name": form.instance.name,'role': admin.get_role_display()}
        return JsonResponse({"status": True})
    return JsonResponse({"status": False, "error": form.errors})

# 用户重置密码
def user_reset(request,aid):
    admin = models.Admin.objects.filter(id=aid).first()
    if not admin:
        # return render(request, 'error.html', {"msg": "数据不存在"})
        # return redirect("/yibiao/list/")
        return redirect("/")
    title = "重置密码 - {}".format(admin.username)
    req_method = request.method
    if req_method == 'GET':
        # form = AdminResetModelForm(instance=admin)      # 更新密码
        form = AdminResetModelForm()      #重置密码不让她看到原来的密码，让其显示为空
        return render(request, 'public_xxx_add.html', {"title": title,"form": form})
    form = AdminResetModelForm(data=request.POST,instance=admin)
    if form.is_valid():
        form.save()
        return redirect("/")
        # return redirect("/yibiao/list/")
    return render(request, 'public_xxx_add.html', {"title": title, "form": form})

django_yibiao/my_app/views/meter.py
# 姓名：刘超
# 开发时间：2022/7/13 15:25
# -*- coding: utf-8 -*-
from django.shortcuts import render, HttpResponse, redirect

def index(request):
    return render(request,"hello.html")

django_yibiao/my_app/views/ocr.py
# 姓名：刘超
# 开发时间：2022/7/19 15:05
# -*- coding: utf-8 -*-
from django.shortcuts import render,HttpResponse,redirect
from my_app.utils.pagination import Pagination
from my_app import models
from my_app.utils.bootstrap import BootStrapModelForm
from django import forms
from django.http import JsonResponse
from yibiao_ocr.img_ocr_rec import ocr_rec
import os
import glob

# 免除post请求的csrf认证
from django.views.decorators.csrf import csrf_exempt

'''图片上传的ModelForm'''
class OcrImgModelForm(BootStrapModelForm):

    bootstrap_exclude_fields = ["img"]  # 排除不想添加样式的字段

    class Meta:
        model = models.ImgOcrRec
        exclude = ["img_result", "admin"]  # 排除img_result和admin后的所有属性（排除订单号和所属用户）
        widgets = {
            "img": forms.FileInput(attrs={"accept": "image/*"}),
            # 限制input file上传类型只能是图片: <input type="file" accept="image/*">
        }

'''ocr文字识别列表'''
def ocr(request):
    form = OcrImgModelForm()
    return render(request,'ocr.html',{"form": form})

'''识别'''
@csrf_exempt
def rec(request):
    form = OcrImgModelForm(data=request.POST, files=request.FILES)

    try:
        if form.is_valid():
            # 固定设置管理员ID，去哪里获取？(当前登录用户的id)
            form.instance.admin_id = request.session["info"]["id"]
            form.save()
            yid = form.instance.id
            name = str(form.instance.img)  # rec/1.jpg
            result = ocr_rec(name)
            print(result)
            models.ImgOcrRec.objects.filter(id=yid).update(img_result=result)

            os.chdir('E:\python\django_yibiao')  # 因为ocr可能改变了，改变工作目录
            return JsonResponse({"status": True, "msg": result, "url": name})

        return JsonResponse({"status": False, "error": form.errors})
    except Exception as e:
        os.chdir('E:\python\django_yibiao')  # 因为ocr可能改变了，改变工作目录
        return JsonResponse({"status": False,"msg": "生成失败，数据异常"})


'''ocr文字识别列表'''
def ocr_list(request):
    user_id = request.session["info"]["id"]
    queryset = models.ImgOcrRec.objects.filter(admin_id=user_id).order_by("-id")
    page_object = Pagination(request,queryset,page_size=5)
    context = {
        "queryset": page_object.page_queryset,  # 分完页的数据
        "page_string": page_object.html()  # 生成页码
    }
    return render(request, 'ocr_list.html', context)

def ocr_del(request):
    '''删除图片'''
    tid = request.GET.get("uid")
    Img_ocr = models.ImgOcrRec.objects.filter(id=tid).first()
    if not Img_ocr:
        return JsonResponse({"status": False, "error": "删除失败，数据不存在"})

    img_name = str(Img_ocr.img)  # rec/1.png
    # print(img_name)  # rec/001_bwajbah.jpg
    # print(os.getcwd())  # E:\python\django_yibiao
    os.chdir('E:\python\django_yibiao')  # 改变工作目录
    paths = glob.glob(os.path.join('yibiao_ocr', img_name))
    # 删除名称为img_name图像
    for file in paths:
        # print(file)   # yibiao_ocr/TemplateLib/code.png
        os.remove(file)

    models.ImgOcrRec.objects.filter(id=tid).delete()
    return JsonResponse({"status": True})

django_yibiao/my_app/templates/admin_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px;" class="clearfix">
            {#            <a class="btn btn-success" href="#" target="_blank">  <!-- 在新的页面打开 -->#}
            <a class="btn btn-success" href="/admin/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新建用户
            </a>

            <div style="float: right;width: 300px;">
                <form href="/admin/list/" method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="关键字"
                               value="{{ search_data }}">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </span>
                    </div>
                </form>
            </div>

            {#            <a class="btn btn-success" href="/user/model/form/add/">#}
            {#                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>#}
            {#                新建用户ModelForm#}
            {#            </a>#}

        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span> 管理员列表
            </div>

            <!-- Table -->
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>id</th>
                    <th>用户名</th>
                    <th>密码</th>
                    <th>姓名</th>
                    <th>年龄</th>
                    <th>性别</th>
                    <th>手机号</th>
                    <th>用户角色</th>
                     <th>创建时间</th>
                    <th>重置密码</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>

                {% for admin in admin_list %}
                    <tr>
                        <th scope="row">{{ admin.id }}</th>
                        <td>{{ admin.username }}</td>
{#                        <td>{{ admin.password }}</td>#}
                        <td>{{ admin.username }}</td>
                        <td>{{ admin.name }}</td>
                        <td>{{ admin.age }}</td>
                        <td>{{ admin.get_gender_display }}</td>
                        <td>{{ admin.mobile }}</td>
                        <td>{{ admin.get_role_display }}</td>
                        <td>{{ admin.create_time }}</td>
                        <td>
                            <a href="/admin/{{ admin.id }}/reset/" class="btn btn-primary btn-xs">重置密码</a>
                        </td>
                        <td>
                            <a href="/admin/{{ admin.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                            {#                            <a href="/admin/{{ admin.id }}/up/" class="btn btn-primary btn-xs">编辑</a>#}
                            {#                            <a href="/admin/up/?id={{ user.id }}" class="btn btn-primary btn-xs">编辑</a>#}
                            <a href="/admin/del/?id={{ admin.id }}" class="btn btn-danger btn-xs">删除</a>
                        </td>

                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <!-- 分页 -->

        <div class="clearfix">
            <ul class="pagination" style="float: left;">
                {{ page_string }}
            </ul>
        </div>

    </div>
{% endblock %}

django_yibiao/my_app/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ msg }}</div>
    </div>
{% endblock %}

django_yibiao/my_app/templates/hello.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container">
        <h1>hello</h1>
    </div>
{% endblock %}

django_yibiao/my_app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .account {
            width: 400px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: auto;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
        }

        .account h2 {
            margin-top: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="account">
    <h2>用户登录</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>用户名</label>
            {{ form.username }}
            <span style="color: red;">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>密码</label>
            {{ form.password }}
            <span style="color: red;">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label for="id_code">图片验证码</label>
            <div class="row">
                <div class="col-xs-7">
                    {{ form.code }}
                    <span style="color: red;">{{ form.code.errors.0 }}</span>
                </div>
                <div class="col-xs-5">
                    <img id="image_code" src="/image/code/" style="width: 125px;">
                </div>
            </div>
        </div>
        <input type="submit" value="登 录" class="btn btn-primary" style="margin-left: 24%;margin-right: 15%;">
        <a href="/user/add/" class="btn btn-primary">注册</a>
    </form>

</div>

</body>
</html>

django_yibiao/my_app/templates/my_message.html
{% extends 'layout.html' %}

{% load static %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form id="FormAdd" novalidate>  <!-- novalidate把游览器的校验关闭 -->
                    <!--不加会报错，这是django的校验-->
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>{{ field.label }}</label>
                                    {{ field }}
                                    <!--表示只显示第一个错误： field.errors.0 -->
                                    <span style="color: red;">{{ field.errors.0 }}</span>
                                </div>
                            </div>
                        </div>
                    {% endfor %}

                    <button id="btnSave" type="button" class="btn btn-primary">提 交</button>

                </form>
                <a href="/user/{{ request.session.info.id }}/reset/" class="btn btn-primary" style="margin-top: 25px;margin-right: 25px;">重置密码</a>
{#                <a href="/yibiao/list/" class="btn btn-primary" style="margin-top: 25px;">返回主页</a>#}
                <a href="/" class="btn btn-primary" style="margin-top: 25px;">返回主页</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript">
        $(function () {
            // 页面框架加载完成之后代码自动执行
            bindBtnEvent();
        })
        
        function bindBtnEvent() {
            $("#btnSave").click(function () {
                // 向后台发送请求
                $.ajax({
                    url: "/user/" + {{ request.session.info.id }} + "/edit/",
                    type: "post",
                    data: $("#FormAdd").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            alert("修改成功");
                            // 清空对话框中的数据
                            $("#FormAdd")[0].reset();
                            // 用js实现页面刷新
                            location.reload();
                        } else {
                            $.each(res.error, function (name, errorList) {
                                // errorList是因为错误信息是一个数组
                                // ModelForm会自动创建一个id，比如：id="id_title"
                                // next()是下一个标签
                                $("#id_" + name).next().text(errorList[0]);
                            })
                        }
                    }

                });
            })
        }
        
        
    </script>
{% endblock %}

{#{% block js %}#}
{#    <script src="{% static 'plugins/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>#}
{#    <script src="{% static 'plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>#}
{#    <script src="static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>#}
{#    <script src="static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>#}
{#    <script type="text/javascript">#}
{#        $(function () {#}
{#            $('.dt').datepicker({#}
{#                format: 'yyyy-mm-dd',#}
{#                // startDate: '0',    // 表示开始时间从当前时间开始#}
{#                language: "zh-CN",#}
{#                autoclose: true#}
{#            });#}
{#        });#}
{#    </script>#}
{#{% endblock %}#}